FROM docker.io/louislam/uptime-kuma:1.23.4-debian@sha256:786ec92a089f0ea67ea912983e30f1869a2eba4b5ee880e1f013966b7eb09112 AS app-donor

FROM docker.io/node:21.2.0-bullseye-slim@sha256:cc16ec9e9a785fe0a185ac07d121327fd0efe4f588a55297362a5d4a9a347013

ARG UID=3310
ARG GID=3310

# renovate: datasource=pypi depName=apprise versioning=pep440
ARG APPRISE_VERSION=1.6.0

# renovate: datasource=github-releases depName=cloudflare/cloudflared
ARG CLOUDFLARED_VERSION=2023.8.1

COPY --from=app-donor /app /app

RUN apt-get update -qqy \
    # Install Uptime-Kuma dependencies
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -qqy \
        python3 python3-pip python3-cryptography python3-six python3-yaml python3-click python3-markdown python3-requests python3-requests-oauthlib \
        sqlite3 iputils-ping util-linux dumb-init curl ca-certificates bash \
    && pip3 --no-cache-dir install apprise==${APPRISE_VERSION} \
    && rm -rf /var/lib/apt/lists/* \
    \
    # Download and install cloudflared
    && ARCH= && dpkgArch="$(dpkg --print-architecture)" \
    && case "${dpkgArch##*-}" in \
      amd64) ARCH='amd64';; \
      arm64) ARCH='arm64';; \
      armhf) ARCH='arm';; \
      *) echo "unsupported architecture"; exit 1 ;; \
    esac \
    && curl -fsSLo /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-${ARCH} \
    && chmod +x /usr/local/bin/cloudflared \
    \
    # Setup non-root system account + group
    && addgroup --system --gid ${GID} uptime-kuma || true \
    && adduser --system --disabled-login --ingroup uptime-kuma --no-create-home --home /nonexistent --gecos "uptime-kuma" --shell /bin/false --uid ${UID} uptime-kuma || true \
    && mkdir -p /app/data \
    && chown -R uptime-kuma:0 /app \
    && chmod -R g=u /app \
    \
    # Smoke Tests
    && set -ex || exit $?; \
      cloudflared version; \
      apprise --version;

ENV HOME=/app
WORKDIR /app
USER uptime-kuma
EXPOSE 3001
VOLUME ["/app/data"]
CMD ["/usr/bin/dumb-init", "--", "node", "server/server.js"]
