apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  namespace: {{ include "uptime-kuma.namespace" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
