name: "♻️ Cleanup GHCR"
# see also https://github.com/marketplace/actions/container-retention-policy

on:
  schedule:
    - cron: "0 0 * * 0"  # At 00:00 on Sunday.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cleanupGhcr:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old unused container images
        uses: snok/container-retention-policy@v2
        id: retention
        with:
          image-names: uptime-kuma
          cut-off: A week ago UTC
          timestamp-to-use: updated_at
          account-type: personal
          keep-at-least: 4
          skip-tags: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Output
        run: |-
          echo "Failed cleanup for = ${{ steps.retention.outputs.failed }}"
          echo "Needs manual cleanup = ${{ steps.retention.outputs.needs-github-assistance }}"
