name: "🏗️ Container multi-Image Build"

on:
  pull_request:
    branches:
      - main
    paths:
      - container/**
  push:
    branches:
      - main
    paths:
      - container/**
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: false
        required: true
        description: "Push the image after the build?"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install qemu dependency
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Get Uptime-Kuma Version
        run: |-
          VERSION=`sed -nr "s;.*docker.io/louislam/uptime-kuma:(.*)-debian.*;\1;p" container/Containerfile`
          echo "APP_VERSION=${VERSION}"
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - id: container
        name: Build Container Image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: uptime-kuma
          tags: >-
            ${{ env.APP_VERSION }}
          oci: true
          platforms: linux/amd64, linux/arm64
          containerfiles: |-
            container/Containerfile

      - name: Push container image to ghcr.io
        if: ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)) && github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          platforms: linux/amd64, linux/arm64
          image: ${{ steps.container.outputs.image }}
          tags: ${{ steps.container.outputs.tags }}
          labels: ${{ steps.container.outputs.labels }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

